### PR TITLE
Update pl.json

### PR DESCRIPTION
**Pull request by Lioheart**
Update Polish translate

### CODE REVIEW

**Comment by Eligarf** [comment]
I adjusted the error messages to better handle substitutions. I hoped I'd finish before you did the translation, but it didn't work out that way.

**Comment by Lioheart** [comment]
I understand. I hope this can be resolved.

**Comment by Eligarf** [comment]
You need to pull the latest and resolve the conflict on your end. I'll then pull it into main.

**Comment by Lioheart** [comment]
Ok, I'll close this, I'll add it again with a new translation

**Pull request closed without merging**
